#ifndef BLINKYBUTTONERROR_H
#define BLINKYBUTTONERROR_H

#define ERR_DIFFERENT_FUNCTION_CALLED 1
#define ERR_DIFFERENT_INPUT_PARAMETER 2
#define ERR_SEQUENCE_STOP 3
#define ERR_FUNCTION_CALLED 4
#endif // BLINKYBUTTONERROR_H
